ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [br.com.madeireira.ApplicationKt.module]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/madeireira"
    url = ${?DB_URL}
    user = "postgres"
    user = ${?DB_USER}
    password = "admin"
    password = ${?DB_PASSWORD}
}
