package br.com.madeireira.modules.estoque.domain.model

enum class TipoMovimentacao {
    ENTRADA_COMPRA, SAIDA_VENDA, RESERVA, LIBERACAO_RESERVA,
    AJUSTE_POSITIVO, AJUSTE_NEGATIVO, PERDA,
    TRANSFERENCIA_SAIDA, TRANSFERENCIA_ENTRADA,
    SOBRA_ENTRADA, DEVOLUCAO_ENTRADA, DEVOLUCAO_SAIDA
}
